import Toast from "./components/atoms/Toast";
import AuthContext from "./contexts/AuthContext";
import Header from "./components/atoms/Header";
import QueryContext from "./contexts/QueryContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ 
  subsets:["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toast />
        <AuthContext>
          <QueryContext>
            <div className="min-h-full">
              <Header />
              {children}
            </div>
          </QueryContext>
        </AuthContext>
      </body>
    </html>
  );
}
