name: Docker Image CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get latest commit short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tingress-front:${{ steps.vars.outputs.sha_short }}
        build-args: |
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          API_URL=${{ secrets.API_URL }}
        cache-from: type=gha
        cache-to: type=gha,mode=max