name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      roting-db:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - 5432:5432

      roting-servcer:
        image: ap95071/rotingtest:latest
        env:
          SECRET_KEY_BASE: ${SECRET_KEY_BASE}
          DATABASE_URL: ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@roting-db/${POSTGRES_DB}
        ports:
          - 4000:4000

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --progress=plain --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v6
      with:
         context: .
         platforms: linux/amd64, linux/arm64
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/rotingfronttest:latest
         
